#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#       pacman
#       
#       Copyright 2010 Raphael Michel <webmaster@raphaelmichel.de>
#       
#       This program is free software; you can redistribute it and/or modify
#       it under the terms of the GNU General Public License as published by
#       the Free Software Foundation; either version 2 of the License, or
#       (at your option) any later version.
#       
#       This program is distributed in the hope that it will be useful,
#       but WITHOUT ANY WARRANTY; without even the implied warranty of
#       MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#       GNU General Public License for more details.
#       
#       You should have received a copy of the GNU General Public License
#       along with this program; if not, write to the Free Software
#       Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#       MA 02110-1301, USA.

import curses, pacman, locale
locale.setlocale(locale.LC_ALL,"")

def keyloop(stdscr):
	stdscr.clear()
	curses.start_color()
	stdscr_y, stdscr_x = stdscr.getmaxyx()
	menu_y = (stdscr_y-2)-1
	
	subwin = stdscr.subwin(stdscr_y-2, stdscr_x, 0, 0)

	pac = pacman.Pacman(subwin, stdscr)
	pac.display_menu(stdscr, menu_y)

	# Main loop:
	while (1):  
		c = stdscr.getch()        
		if 0<c<256:
			c = chr(c)
			if c in 'Qq':
				break
			elif c in 'Oo':
				pac.statusline('ERROR: Not yet implemented!', 2)
			elif c in 'Hh':
				pac.statusline('ERROR: Not yet implemented!', 2)
			elif c in 'Rr':
				pac.start_game('data/default.pacman')
			elif c in 'Cc':
				pac.display_credits()
			else: pass        
		elif c == curses.KEY_UP: pac.move(curses.KEY_UP)
		elif c == curses.KEY_DOWN: pac.move(curses.KEY_DOWN)
		elif c == curses.KEY_LEFT: pac.move(curses.KEY_LEFT)
		elif c == curses.KEY_RIGHT: pac.move(curses.KEY_RIGHT)
		else:
			pass         

def main(stdscr):
	keyloop(stdscr)
	return 0

if __name__ == '__main__':
    curses.wrapper(main)
