#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#       pacman
#       
#       Copyright 2010 Raphael Michel <webmaster@raphaelmichel.de>
#       
#       This program is free software; you can redistribute it and/or modify
#       it under the terms of the GNU General Public License as published by
#       the Free Software Foundation; either version 2 of the License, or
#       (at your option) any later version.
#       
#       This program is distributed in the hope that it will be useful,
#       but WITHOUT ANY WARRANTY; without even the implied warranty of
#       MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#       GNU General Public License for more details.
#       
#       You should have received a copy of the GNU General Public License
#       along with this program; if not, write to the Free Software
#       Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#       MA 02110-1301, USA.

import curses, pacman, locale, sys, os
from time import sleep
import thread
locale.setlocale(locale.LC_ALL,"")

pac = None
t = None
a = 0

def keyloop(stdscr):
	# Main loop:
	while (1):  
		try:
			c = stdscr.getch()     
		except KeyboardInterrupt:
			break   
		if 0<c<256:
			c = chr(c)
			if c in 'Qq':
				break
			elif c in 'Oo':
				pac.statusline('ERROR: Not yet implemented!', 2)
			elif c in 'Hh':
				pac.statusline('ERROR: Not yet implemented!', 2)
			elif c in 'RrSs':
				pac.start_game('data/default.pacman')
			elif c in 'Cc':
				pac.display_credits()
			elif c in 'Bb':
				pac.back()
			elif c in 'Pp':
				pac.toggle_pause()
			else: pass        
		elif c == curses.KEY_UP: pac.move(curses.KEY_UP)
		elif c == curses.KEY_DOWN: pac.move(curses.KEY_DOWN)
		elif c == curses.KEY_LEFT: pac.move(curses.KEY_LEFT)
		elif c == curses.KEY_RIGHT: pac.move(curses.KEY_RIGHT)
		else:
			pass    
			

def timer():
	global pac,a
	sleep(1)
	a += 1
	timer()
	
def main(stdscr):
	global pac, t
	
	stdscr.clear()
	curses.start_color()
	stdscr_y, stdscr_x = stdscr.getmaxyx()
	menu_y = (stdscr_y-2)-1
	
	subwin = stdscr.subwin(stdscr_y-2, stdscr_x, 0, 0)

	pac = pacman.Pacman(subwin, stdscr)
	pac.display_startmenu(stdscr, menu_y)
	
	t = thread.start_new_thread(timer, ())
	
	keyloop(stdscr)
	
	thread.exit()
	
	#t_main = Thread(target = keyloop, args = (stdscr,))
	#t_main.start()
	
	#t_timer = Thread(target = timer)
	#t_timer.start()
	
	#while True:
	#	if not t_main.isAlive or not t_timer.isAlive:
	#		break
	
	return 0

if __name__ == '__main__':
	curses.wrapper(main)
	print a
